version: '3'
services:
  postgres:
    image: postgres
    environment: &postgres_env
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: demo
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: always