spring:
  flyway:
    enabled: true
  jpa:
    database: postgresql
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  http:
    log-request-details: true
management:
  endpoints:
    web:
      exposure:
        include: mappings